image: docker:stable

services:
  - name: docker:dind
    alias: docker
  

before_script:
  - apk add --no-cache python3 py3-pip
  - pip install awscli


stages:
  - build
  #- deploy

build:
  stage: build
  # rules: 
  #     - if: '$CI_COMMIT_BRANCH == "develop"'
  tags:
      - holdco
  script:
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
    - docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

  only:
    - develop
